export const GET_FIRST_QUESTION = "GET_FIRST_QUESTION";
export const GET_FIRST_QUESTION_SUCCESS = 'GET_FIRST_QUESTION_SUCCESS'

export const UPDATE_VAL = 'UPDATE_VAL'
export const GPT_SEND_DATA = 'GPT_SEND_DATA'
export const GPT_SEND_DATA_SUCCESS = 'GPT_SEND_DATA_SUCCESS'

export const SET_IS_CHAT = 'SET_IS_CHAT'
export const GET_CURRENT_QA = 'GET_CURRENT_QA'
export const GET_CURRENT_QA_SUCCESS = 'GET_CURRENT_QA_SUCCESS'

export const SWITCH_GO_FOME = 'SWITCH_GO_FOME'
export const SWITCH_GO_FOME_SUCCESS = 'SWITCH_GO_FOME_SUCCESS'

export const SET_QA_DATA = 'SET_QA_DATA'
