export const SET_BLOGS = "SET_BLOGS";
export const SET_LATEST_BLOGS = 'SET_LATEST_BLOGS'
export const SET_ANOTHER_BLOGS = 'SET_ANOTHER_BLOGS'
export const GET_RECOMMEND_BLOGS = 'GET_RECOMMEND_BLOGS'
export const GET_RECOMMEND_BLOGS_SUCCESS = 'GET_RECOMMEND_BLOGS_SUCCESS'

export const GET_BLOG_BYID = 'GET_BLOG_BYID'
export const GET_BLOG_BYID_SUCCESS = 'GET_BLOG_BYID_SUCCESS'
