import React, { useState } from 'react';

import styles from './styles.module.scss';
import addIcon from '../../../../assets/images/home/faq/add.svg';
import claseIcon from '../../../../assets/images/icons/clase.png';

import Collapes from './Collapes'


const questions = [

  {
    title: "Is it safe to use Passdown for creating my will?",
    content: "Absolutely. We take your privacy and security very seriously. All your data is encrypted and stored securely, and we follow strict protocols to ensure your information is always protected."
  },
  {
    title: "Do I need to have legal knowledge to use the free will tool?",
    content: "Not at all. Our tool is designed to be accessible for everyone, regardless of legal knowledge. The platform provides easy-to-understand explanations for each step of the process, making it simple to create your will."
  },
  {
    title: "Can I update or change my will after it's been created with Passdown?",
    content: "Yes, you can. Our platform allows you to revisit and revise your will as your circumstances change. However, it's essential to remember that changes must comply with legal regulations for them to be valid."
  },
  {
    title: "Is the will I create with Passdown legally binding?",
    content: "Yes. The wills generated by Passdown are designed to be legally valid. However, for it to become legally binding, you need to print it, sign it, and have it witnessed according to the laws of your state or country. If you're uncertain about this process, we recommend consulting with a legal professional."
  },

]

const FAQ = () => {

  const [open, setOpen] = useState(true)

  const openContent = () => {
    setOpen(true)
  }

  const closeContent = () => {
    setOpen(false)
  }


  return (
    <section className={styles.faq}>
      <div className={styles.wrapper}>
        <div className={styles.content}>
          <p className={styles.upper_heading}>All answers are here</p>
          <h1>Frequently Asked Questions </h1>
          <p className={styles.description}>Got Questions? We've Got Answers! Let's Simplify Your Passdown Journey Together.</p>
        </div>
        <div className={styles.questions}>
          <div className={`${styles.question}`}>
            <h6 className={styles.question_title}>How does Passdown's free will tool work?</h6>

            {open && (
              <p className={styles.question_content}>Passdown's will tool is designed to be straightforward and user-friendly. After creating an account, you'll be guided through a series of questions tailored to your unique circumstances. Once you've answered all the questions, our tool will generate a comprehensive will that meets your specific needs.</p>
            )}

            {open ? (
              <img src={claseIcon} alt="Open Close Icon" style={{ cursor: 'pointer' }} onClick={closeContent} />
            ) : (
              <img src={addIcon} alt="Open Close Icon" style={{ cursor: 'pointer' }} onClick={openContent} />
            )}
          </div>

          {questions.map((item, index) => {
            return (
              <Collapes key={index} title={item.title} content={item.content} />
            )
          })}

        </div>
      </div>
    </section>
  )
}

export default FAQ